import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging.tracer.byteswrite.com/login');
  await page.getByRole('textbox', { name: 'Enter your Employee Id' }).click();
  await page.getByRole('textbox', { name: 'Enter your Employee Id' }).fill('E2401010004');
  await page.getByRole('textbox', { name: 'Enter Your Password' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page).toHaveURL(/.*dashboard/);
  await page.locator('a[href="/user/publications"]').click();
  await expect(page).toHaveURL(/.*publications/);
  await page.getByRole('link', { name: 'Journal Papers' }).click();
  await expect(page).toHaveURL(/.*journals/);
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(2).click();
  await expect(page).toHaveURL(/.*add/);
  await page.getByRole('textbox', { name: 'Enter paper title' }).click();
  await page.getByRole('textbox', { name: 'Enter paper title' }).fill('Randomxyz');
  await page.getByRole('textbox', { name: 'Enter journal title' }).click();
  await page.getByRole('textbox', { name: 'Enter journal title' }).fill('Randomxyz');
  await page.getByRole('combobox').filter({ hasText: 'Select Publisher Name' }).click();
  await page.locator('div').filter({ hasText: /^American Bar Association \(ABA\)$/ }).first().click();
  await page.getByRole('combobox').filter({ hasText: 'Enter journal type' }).click();
  await page.getByRole('option', { name: 'International' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select Author Type' }).click();
  await page.getByRole('option', { name: 'Organizational Researcher' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select Author Name' }).click();
  await page.locator('div').filter({ hasText: /^Arjun Sachin AmbavaneE2401010004$/ }).first().click();
  await page.getByRole('combobox').filter({ hasText: 'Enter tags' }).click();
  await page.locator('div').filter({ hasText: /^5G Networks$/ }).first().click();
  await page.locator('input[name="eISSN"]').click();
  await page.locator('input[name="eISSN"]').fill('1234-5678');
  await page.getByRole('combobox').filter({ hasText: 'Enter category' }).click();
  await page.getByRole('option', { name: 'Submitted' }).click();
  await page.getByRole('button', { name: 'Select submitted date' }).click();
  await page.getByRole('gridcell', { name: '1', exact: true }).first().click();
  await page.getByRole('textbox', { name: 'Enter journal URL' }).click();
  await page.getByRole('textbox', { name: 'Enter journal URL' }).fill('https://test.com');
  await page.getByRole('combobox').filter({ hasText: 'Select Provider' }).click();
  await page.getByRole('option', { name: 'Web of Science' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select Wos Index' }).click();
  await page.getByLabel('Emerging Sources Citation').getByText('Emerging Sources Citation').click();
  await page.getByRole('textbox', { name: 'Enter Impact Factor' }).click();
  await page.getByRole('textbox', { name: 'Enter Impact Factor' }).fill('1');
  await page.getByRole('combobox').filter({ hasText: 'Select Affiliation Details' }).click();
  await page.locator('div').filter({ hasText: /^Aspire Organization, Pune$/ }).first().click();
  await page.getByRole('button', { name: 'Submit Details' }).click();
  await expect(page).toHaveURL(/.*journals/);
  await page.getByText('Randomxyz', { exact: true }).click();
});